<?php

namespace Mateusz\MedicalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PatientRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PatientRepository extends EntityRepository
{
}
