#MateuszMedicalBundle:
#    resource: "@MateuszMedicalBundle/Resources/config/routing.yml"
#    type:     annotation
#    prefix:   /

patient:
     pattern:  /patient/new
     defaults: { _controller: MateuszMedicalBundle:Patient:new }

clinic_new:
     pattern:  /clinic/new
     defaults: { _controller: MateuszMedicalBundle:Clinic:new }

clinic_edit:
    pattern:  /clinic/edit/{id}
    defaults: { _controller: MateuszMedicalBundle:Clinic:edit }
