#MateuszMedicalBundle:
#    resource: "@MateuszMedicalBundle/Resources/config/routing.yml"
#    type:     annotation
#    prefix:   /

patient:
     pattern:  /patient/new
     defaults: { _controller: MateuszMedicalBundle:Patient:new }
